# Generated by Django 3.0.3 on 2021-05-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0007_auto_20200325_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateField(max_length=30, null=True),
        ),
    ]
