# Generated by Django 3.0.3 on 2021-05-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0008_auto_20210510_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
