# Generated by Django 3.0.3 on 2021-05-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0011_auto_20210510_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateField(null=True),
        ),
    ]
